services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - web
    depends_on:
      - postgres
    command: pnpm run dev

  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PSWD}
    healthcheck:
      test: rabbitmq-diagnostics --quiet check_running && rabbitmq-diagnostics --quiet check_local_alarms
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - web
      
  workers:
    container_name: workers
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - web
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: pnpm run workers

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ~/.n8n:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_EDITOR_BASE_URL=${WEBHOOK_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
    restart: always
    networks:
      - web
    
  ngrok:
    image: ngrok/ngrok:latest
    network_mode: "host"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http --domain=${WEBHOOK_DOMAIN} 5678
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  redisdata:

networks:
  web:
    driver: bridge